set-option -g default-terminal 'tmux-256color'
set-option -g terminal-overrides ',xterm-256color:RGB'
set -g status-position top
set -g status-right ""
set -g base-index 1
set -g escape-time 0
set -g renumber-windows on
setw -g mode-keys vi

unbind C-b 
set -g prefix C-Space
bind C-Space send-prefix
bind f resize-pane -Z
bind s split-window -v
bind v split-window -h
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind-key x kill-pane

set -g @plugin "tmux-plugins/tpm"
set -g @plugin 'catppuccin/tmux#v2.3.1' 
set -g @catppuccin-flavor 'mocha'
set -g @catppuccin_window_text " #W#{?window_zoomed_flag,(󰍋),}"
set -g @catppuccin_window_current_text " #W#{?window_zoomed_flag,(󰍋),}"
run '~/.tmux/plugins/tpm/tpm'

# These are for making commands and messages take up the entire statusbar
set -g message-style "fg=#cdd6f4,bg=#1e1e2e,fill=#1e1e2e"
set -g message-command-style "fg=#cdd6f4,bg=#1e1e2e,fill=#1e1e2e"  
